Repository koenhendriks/ha-button-plus, pull requests merged in 2024-01, with the labels that each got.

#23 Add label support over MQTT
  custom_components/button_plus/__init__.py
  custom_components/button_plus/button.py
  custom_components/button_plus/button_plus_api/event_type.py
  custom_components/button_plus/buttonplushub.py
  custom_components/button_plus/config_flow.py
  custom_components/button_plus/resource/push config.txt
  custom_components/button_plus/text.py
Labels: enhancement

#27 Retain label values when published over MQTT
  custom_components/button_plus/text.py
Labels: bug

#29 Use connections from device config to setup hass devices
  custom_components/button_plus/button.py
  custom_components/button_plus/config_flow.py
  custom_components/button_plus/light.py
  custom_components/button_plus/switch.py
  custom_components/button_plus/text.py
Labels: enhancement

#35 Write label state to home assistant
  custom_components/button_plus/text.py
Labels: bug

#38 Multiple automation triggered with multiple B+
  custom_components/button_plus/coordinator.py
Labels: bug

#40 Add hub_id as prefix for entity identifier.
  custom_components/button_plus/button.py
  custom_components/button_plus/buttonplushub.py
  custom_components/button_plus/light.py
  custom_components/button_plus/switch.py
  custom_components/button_plus/text.py
Labels: bug, enhancement
